create table AUCTION_ITEMS (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
	title
	category
	picture
	description
	address
	reservePrice
	startPrice
	bidIncrements
	endTime
	


);
